---
version: 3
images:
  base_image:
    name: registry.fedoraproject.org/fedora-minimal:latest
dependencies:
    python_interpreter:
      package_system: python3
    ansible_core:
        package_pip: ansible-core
    ansible_runner:
      package_pip: ansible-runner
options:
  package_manager_path: dnf5
