---
name: Build and push images to Github Container Registry
on:
  push:
    branches:
      - devel
  schedule:
    - cron: '* * * * 6'  # Friday

jobs:
  push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      issues: write
    steps:
      - uses: actions/checkout@v2

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: install dependencies
        run: pip install ansible-builder

      - name: Build zen image
        run: ansible-builder build -v3 --tag=ghcr.io/alancoding/zen-ee --container-runtime=docker

      - name: Push images
        run: docker push ghcr.io/alancoding/zen-ee:latest

      - name: The job has failed
        uses: JasonEtco/create-an-issue@v2
        if: ${{ failure() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
